
kind: pipeline
name: Built Bot

steps:
- name: build
  image: baalajimaestro/android_build:latest
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - bash setup.sh
  - github-release upload --owner koumaza --repo gb --tag "$(date)" --name "$(date)" --body "$(date)"
