---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ubuntu:latest
  commands:
  - bash setup.sh
  - github-release upload --owner koumaza --repo gb --tag "$(date)" --name "$(date)" --body "$(date)"
